name: skilllab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Remove webview_flutter as it's not needed for these approaches
  provider: ^6.1.2
  url_launcher: ^6.0.0 # Only needed for Deep Linking

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http: ^0.13.3
  image_picker: ^0.8.6+1

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/images/skilllablogo.png
   
